/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OpenInGitHubPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var customIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/>
<path d="M9 18c-4.51 2-5-2-7-2"/>
<g transform="translate(12 12) scale(0.5)" stroke="currentColor">
  <path d="M21 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6"/>
  <path d="m21 3-9 9"/>
  <path d="M15 3h6v6"/>
</g>
</svg>
`;
var CONSTS = {
  TITLE_ID: "open-in-github",
  TITLE: "Open in GitHub"
};
var GIT_DIR = ".git";
var GIT_CONFIG_PATH = `${GIT_DIR}/config`;
var GIT_HEAD_PATH = `${GIT_DIR}/HEAD`;
var OpenInGitHubPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    /**
     * open github in browser
     * @param evt The mouse event that triggered the action
     * @param file The file context (optional), if triggered from file/editor menu
     */
    this.openGitHub = async (evt, file) => {
      try {
        const targetFile = file;
        const openFileInRepo = !!targetFile;
        const repoUrl = await this.getGitHubRepoUrl();
        if (!repoUrl) {
          return;
        }
        if (openFileInRepo && targetFile) {
          const filePathRelative = targetFile.path;
          let branch = await this.getCurrentBranch();
          if (!branch) {
            branch = "main";
            new import_obsidian.Notice("Could not detect current branch, defaulting to 'main'.");
          }
          const fileUrl = `${repoUrl}/blob/${branch}/${filePathRelative}`;
          window.open(fileUrl, "_blank");
        } else if (!openFileInRepo) {
          window.open(repoUrl, "_blank");
        } else {
          new import_obsidian.Notice("No active file selected to open in GitHub.");
        }
      } catch (err) {
        new import_obsidian.Notice("Failed to open GitHub repository.");
        console.error("OpenInGitHubPlugin Error:", err);
      }
    };
  }
  async onload() {
    this.vaultAdapter = this.app.vault.adapter;
    if (!this.vaultAdapter) {
      console.error("OpenInGitHubPlugin: Vault adapter is not available. Plugin may not work correctly.");
      new import_obsidian.Notice("OpenInGitHubPlugin: Vault adapter not found. Some features might be limited.");
    }
    (0, import_obsidian.addIcon)(CONSTS.TITLE_ID, customIcon);
    this.addRibbonIcon(CONSTS.TITLE_ID, CONSTS.TITLE, (evt) => this.openGitHub(evt));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile) {
          menu.addItem((item) => {
            item.setTitle(CONSTS.TITLE).setIcon(CONSTS.TITLE_ID).onClick((e) => this.openGitHub(e, file));
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        if (view == null ? void 0 : view.file) {
          menu.addItem((item) => {
            item.setTitle(CONSTS.TITLE).setIcon(CONSTS.TITLE_ID).onClick((e) => this.openGitHub(e, view.file));
          });
        }
      })
    );
  }
  /**
   * Get the GitHub repository URL for the current vault using Vault adapter.
   */
  async getGitHubRepoUrl() {
    if (!this.vaultAdapter) {
      new import_obsidian.Notice("Vault adapter not available. Cannot access file system.");
      return null;
    }
    try {
      const gitDirExists = await this.vaultAdapter.exists(GIT_DIR);
      if (!gitDirExists) {
        new import_obsidian.Notice("No .git directory found in the vault root.");
        return null;
      }
      const configPathExists = await this.vaultAdapter.exists(GIT_CONFIG_PATH);
      if (!configPathExists) {
        new import_obsidian.Notice("No .git/config file found.");
        return null;
      }
      const configContent = await this.vaultAdapter.read(GIT_CONFIG_PATH);
      const remoteMatch = configContent.match(/\[remote\s+"origin"\][^[]*?\n\s*url\s*=\s*(.*)/);
      if (!remoteMatch || !remoteMatch[1]) {
        new import_obsidian.Notice('No remote "origin" URL found in .git/config.');
        return null;
      }
      const remoteUrl = remoteMatch[1].trim();
      const githubUrl = this.convertToGitHubUrl(remoteUrl);
      if (!githubUrl) {
        new import_obsidian.Notice('Could not parse GitHub URL from remote "origin".');
        return null;
      }
      return githubUrl;
    } catch (error) {
      console.error("OpenInGitHubPlugin: Error accessing git config:", error);
      new import_obsidian.Notice("Error accessing git configuration.");
      return null;
    }
  }
  /**
   * Convert a Git remote URL to a GitHub web URL.
   */
  convertToGitHubUrl(remoteUrl) {
    let match = remoteUrl.match(/^https?:\/\/github\.com\/([^/]+\/[^/]+?)(?:\.git)?$/);
    if (match) {
      return `https://github.com/${match[1]}`;
    }
    match = remoteUrl.match(/^git@github\.com:([^/]+\/[^/]+?)(?:\.git)?$/);
    if (match) {
      return `https://github.com/${match[1]}`;
    }
    return null;
  }
  /**
   * Get the current branch of the Git repository using Vault adapter.
   */
  async getCurrentBranch() {
    if (!this.vaultAdapter) {
      new import_obsidian.Notice("Vault adapter not available. Cannot access file system.");
      return null;
    }
    try {
      const gitDirExists = await this.vaultAdapter.exists(GIT_DIR);
      if (!gitDirExists) {
        return null;
      }
      const headPathExists = await this.vaultAdapter.exists(GIT_HEAD_PATH);
      if (!headPathExists) {
        new import_obsidian.Notice("No .git/HEAD file found. Cannot determine branch.");
        return null;
      }
      const headContent = (await this.vaultAdapter.read(GIT_HEAD_PATH)).trim();
      const branchMatch = headContent.match(/^ref:\s+refs\/heads\/(.*)/);
      if (branchMatch && branchMatch[1]) {
        return branchMatch[1];
      }
      new import_obsidian.Notice("Could not parse branch name from .git/HEAD.");
      return null;
    } catch (error) {
      console.error("OpenInGitHubPlugin: Error reading git HEAD:", error);
      new import_obsidian.Notice("Error reading git branch information.");
      return null;
    }
  }
};


/* nosourcemap */